language: node_js

# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty

# https://github.com/travis-ci/apt-source-whitelist/pull/208
sudo: required

node_js:
    - "stable"
install:
    - sudo add-apt-repository --yes ppa:neovim-ppa/unstable
    - sudo apt-get -qq update
    - sudo apt-get install -y neovim libcairo2-dev libgif-dev software-properties-common python-software-properties
    - export DISPLAY=':99.0'
    - sh -e /etc/init.d/xvfb start
    - npm run dep
    - uname -a
    - ./node_modules/.bin/tsc --version
    - ./node_modules/.bin/browserify --version
    - ./node_modules/.bin/mocha --version
    - nvim --version
    - electron --version
script:
    - npm run build
    - npm run test
    - npm run e2e
notifications:
    email:
        on_success: never
        on_failure: change
