language: node_js

# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty

# https://github.com/travis-ci/apt-source-whitelist/pull/208
sudo: required

node_js:
    - "stable"
install:
    - sudo add-apt-repository --yes ppa:neovim-ppa/unstable
    - sudo apt-get -qq update
    - sudo apt-get -qq install neovim xvfb libcairo2-dev libgif-dev
    - export DISPLAY=':99.0'
    - sh -e /etc/init.d/xvfb start
    - npm run dep
    - ./node_modules/.bin/tsc --version
    - ./node_modules/.bin/browserify --version
    - ./node_modules/.bin/mocha --version
    - nvim --version
script:
    - npm run build
    - npm run test
    - npm run e2e
