language: node_js

os:
    - linux
    - osx

osx_image: xcode10.2

dist: xenial

node_js:
    - stable

install:
    - ./scripts/travis-ci-install.sh

script:
    - ./scripts/travis-ci-run.sh

notifications:
    email:
        on_success: never
        on_failure: change

addons:
    apt:
        sources:
            - sourceline: 'ppa:neovim-ppa/unstable'
        packages:
            - neovim
            - g++
            - build-essential
            - libcairo2-dev
            - libpango1.0-dev
            - libjpeg-dev
            - libgif-dev
            - librsvg2-dev
        update: true
    homebrew:
        packages:
            - neovim
            - pkg-config
            - cairo
            - pango
            - libpng
            - giflib
            - jpeg
            - librsvg
        update: true
