language: node_js

os:
    - linux
    - osx

# Use macOS 10.12: https://docs.travis-ci.com/user/languages/objective-c/
osx_image: xcode9

dist: xenial

# https://github.com/travis-ci/apt-source-whitelist/pull/208
sudo: required

node_js:
    - "stable"

install:
    - ./scripts/travis-ci-install.sh

script:
    - ./scripts/travis-ci-run.sh

notifications:
    email:
        on_success: never
        on_failure: change

addons:
    apt:
        sources:
            - sourceline: 'ppa:neovim-ppa/unstable'
        packages:
            - neovim
            - g++
            - build-essential
            - libcairo2-dev
            - libpango1.0-dev
            - libjpeg-dev
            - libgif-dev
            - librsvg2-dev
        update: true
    homebrew:
        packages:
            - neovim
            - pkg-config
            - cairo
            - pango
            - libpng
            - giflib
            - jpeg
            - librsvg
        update: true
